### PR TITLE
docs: provide a way to utilize /var/cache/dnf

### LINKED ISSUE #5: please provide a way to download repo metadata
I just wanted to try depchase, finally. I ran the command and realized, I should download repo metadata. Can we get a tool/script to download it for me? Or, would it be possible to utilize `/var/cache/dnf`?

### PR DESCRIPTION
**Pull request by TomasTomecek**
Fixes #5

Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
does it actually work?

**Comment by ignatenkobrain** [comment]
there is some caching stuff which should be avoided to generate...

**Comment by TomasTomecek** [comment]
Yes, I wouldn't open a PR if it didn't.

**Comment by TomasTomecek** [comment]
so? do you want this or not?

**Pull request closed without merging**
