### PR TITLE
cache whatprovides()

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Before:
1668.64user 1.75system 27:54.85elapsed 99%CPU (0avgtext+0avgdata 308940maxresident)k
0inputs+102064outputs (0major+126919minor)pagefaults 0swaps

After:
796.00user 0.56system 13:18.74elapsed 99%CPU (0avgtext+0avgdata 323424maxresident)k
0inputs+102040outputs (0major+123957minor)pagefaults 0swaps

Signed-off-by: Igor Gnatenko <ignatenkobrain@fedoraproject.org>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Since we don't expose API (which is intentional) we can safely assume that pool will not change during run of depchase. Otherwise we would need to do some invalidation mechanisms. If depchase would be written in C, we could have used `pool->whatprovides` directly without any overhead, but...

**Comment by ignatenkobrain** [comment]
@ncoghlan you would probably need something similar in fedmod. But since you expose API, you can't guarantee that pool will not be changed, so you would need to do some invalidation.

**Comment by contyk** [comment]
Looks reasonable. Casually tested and it doesn't appear to break anything either. +1

**Comment by ncoghlan** [comment]
Thanks for the heads-up, issue filed here: https://pagure.io/modularity/fedmod/issue/51

As things turned out, fedmod's also currently CLI-only (the big difference ended up being integrating native support for the dnf level module metadata)

**Pull request merged**
